name = "boergers"
author = "Thomas Boerger"
version = "3.0.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "748dad3e28d528d86bc5083334be4b4dcaa60be1a7fb98545a709af8566e4769"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
